name: Automated Dependency Updates

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  dependencies:
    name: Update Dependencies
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@main
      with:
        msbuild-architecture: x64

    - name: Get Dependencies
      id: getdep
      run: |
        dotnet restore
        $outJson = dotnet list package --outdated --format json | ConvertFrom-Json
        if (!$outJson.projects[0].frameworks) { return }
        echo "pkgupdated=true" >> "$GITHUB_OUTPUT"
        $jsonPack = $outJson.projects[0].frameworks[0].topLevelPackages
        $xmlDoc = [xml](Get-Content -Path SCPBlock.csproj)
        $ns = New-Object System.Xml.XmlNamespaceManager($xmlDoc.NameTable)
        $ns.AddNamespace("ns", $xmlDoc.DocumentElement.NamespaceURI)
        foreach ($pack in $jsonPack){
          $xmlPath = "//ns:PackageReference[@Include='" + $pack.id + "']"
          $node = $xmlDoc.SelectSingleNode($xmlPath, $ns)
          $node.SetAttribute("Version", $pack.latestVersion)
        }
        $xmlDoc.Save("SCPBlock.csproj")
      shell: pwsh

    - name: Test
      id: test
      if: ${{ steps.getdep.outputs.pkgupdated == 'true' }}
      run: msbuild -r SCPBlock.sln -t:rebuild -p:Configuration=Release

    - name: Push
      id: push
      if: ${{ steps.getdep.outputs.pkgupdated == 'true' }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Dependency Updates
