name: Automated Dependency Updates

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  dependencies:
    name: Update Dependencies
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@main
      with:
        msbuild-architecture: x64
      
    - name: modifycsproj
      id: mod
      run: |
        choco install xmlstarlet
        xml ed -u "//PackageReference[@Include = 'EXILED']/@Version" -v "7.2.0" SCPBlock.csproj --inplace
      shell: pwsh

    - name: Test
      id: test
      run: msbuild -r SCPBlock.sln -t:rebuild -p:Configuration=Release

    - name: Push
      id: push
      if: ${{ steps.update.outputs.pkgupdated == 'true' }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Dependency Updates
