name: Automated Dependency Updates

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  dependencies:
    name: Update Dependencies
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@main

    - name: Update
      id: update
      run: |
        dotnet restore
        dotnet list package
        dotnet add package EXILED -v 7.2.0
        dotnet list package 
      shell: bash

    - name: Test
      id: test
      run: msbuild SCPBlock.sln -t:rebuild -p:Configuration=Release

    - name: Push
      id: push
      if: ${{ steps.update.outputs.pkgupdated == 'true' }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Dependency Updates
