name: CI
on: 
  push:
    paths-ignore:
      - '.github/**'

env:
  EXILED_REFERENCES_URL: https://www.exiled.host/build_deps/Master.zip
  EXILED_REFERENCES_PATH: ${{ github.workspace }}/References
  
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@main
      
    - name: Get references
      run: |
          dotnet restore
          Invoke-WebRequest -Uri ${{ env.EXILED_REFERENCES_URL }} -OutFile ${{ github.workspace }}/References.zip
          Expand-Archive -Path References.zip -DestinationPath ${{ env.EXILED_REFERENCES_PATH }}
      shell: pwsh

    - name: Build solution
      env:
        EXILED_REFERENCES: ${{ env.EXILED_REFERENCES_PATH }}
      run: msbuild -r SCPBlock.sln -t:rebuild -property:Configuration=Release
