name: CI
on: 
  push:
    paths-ignore:
      - '.github/**'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@main

    - name: Setup NuGet
      uses: NuGet/setup-nuget@main
        
    - name: Restore Packages
      run: nuget restore SCPBlock.sln

    - name: Build solution
      run: msbuild SCPBlock.sln -t:rebuild -property:Configuration=Release
