name: CI
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@main

    - name: Setup NuGet
      uses: NuGet/setup-nuget@main
        
    - name: Restore Packages
      run: nuget restore SCPBlock.sln

    - name: Build solution
      env:
          EXILED_REFERENCES: ${{ env.EXILED_REFERENCES_PATH }}
      run: msbuild SCPBlock.sln -t:rebuild -property:Configuration=Release
