name: CI
on: push
env:
  EXILED_REFERENCES_URL: https://www.exiled.host/build_deps/Master.zip
  EXILED_REFERENCES_PATH: ${{ github.workspace }}/References
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@main

    - name: Setup NuGet
      uses: NuGet/setup-nuget@main
      
    - name: Get references
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri ${{ env.EXILED_REFERENCES_URL }} -OutFile ${{ github.workspace }}/References.zip
        Expand-Archive -Path References.zip -DestinationPath ${{ env.EXILED_REFERENCES_PATH }}
        
    - name: Restore Packages
      run: nuget restore SCPBlock.sln

    - name: Build solution
      env:
          EXILED_REFERENCES: ${{ env.EXILED_REFERENCES_PATH }}
      run: msbuild SCPBlock.sln -t:rebuild -property:Configuration=Release
